# Pandas Tutorial

Pandas is the most widely used data analysis and manipulation library in Python. It builds on top of NumPy to provide labeled, tabular data structures, the `Series` for a single labeled column and the `DataFrame` for a full table, similar to a spreadsheet or a SQL table.

Pandas is used to load data from files, clean and filter it, transform it by adding or reshaping columns, and summarize it with grouping and aggregation. Under the hood, DataFrame columns are usually stored as NumPy arrays, and you can freely convert between the two with `.to_numpy()` or by building a DataFrame from an array.

## Importing pandas and checking the version

Install pandas with `pip install pandas`. It is conventionally imported as `pd`, and NumPy is often imported alongside it since the two are used together so often.

In [1]:
import pandas as pd
import numpy as np

print("pandas version:", pd.__version__)

pandas version: 2.3.2

## Series, DataFrame, and concatenating data

A `Series` is a one dimensional labeled array, similar to a single spreadsheet column, with an index of labels alongside the values. A `DataFrame` is a two dimensional table, essentially a collection of Series that share the same index, and is the structure you will use most often.

`pd.concat()` combines multiple Series or DataFrames into one. By default it stacks them as new rows; pass `axis=1` to line them up side by side as new columns instead.

In [ ]:
s = pd.Series([10, 20, 30, 40], index=['1', 'b', 'c', 'd'])
print(s)
print("Value at 'b':", s['b'])

# a,b,c,d
# 10,11,12,13 - p1
# 10,23,45,2 - p2

1    10
b    20
c    30
d    40
dtype: int64
Value at 'b': 10

In [3]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore'],
    'Score': [88.5, 92.0, 79.5, 95.0]
}
df = pd.DataFrame(data)
df

      Name  Age       City  Score
0    Alice   25     Lahore   88.5
1      Bob   30    Karachi   92.0
2  Charlie   35  Islamabad   79.5
3    Diana   28     Lahore   95.0

In [4]:
# Concatenating more rows onto the DataFrame
more_data = pd.DataFrame({
    'Name': ['Ethan', 'Farah'], 'Age': [22, 31],
    'City': ['Multan', 'Lahore'], 'Score': [85.0, 90.5]
})
combined = pd.concat([df, more_data], ignore_index=True)
combined

      Name  Age       City  Score
0    Alice   25     Lahore   88.5
1      Bob   30    Karachi   92.0
2  Charlie   35  Islamabad   79.5
3    Diana   28     Lahore   95.0
4    Ethan   22     Multan   85.0
5    Farah   31     Lahore   90.5

## Summary statistics functions

`.describe()` gives a quick table of count, mean, standard deviation, min, max, and quartiles for numeric columns. `.mean()`, `.median()`, `.max()`, `.min()`, and `.std()` compute a single statistic per column. `.value_counts()` counts how often each distinct value appears in a Series, and `.corr()` shows pairwise correlation between numeric columns.

In [5]:
df.describe()

             Age      Score
count   4.000000   4.000000
mean   29.500000  88.750000
std     4.203173   6.714412
min    25.000000  79.500000
25%    27.250000  86.250000
50%    29.000000  90.250000
75%    31.250000  92.750000
max    35.000000  95.000000

In [6]:
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
 3   Score   4 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 260.0+ bytes

         Name        Age    City      Score
count       4   4.000000       4   4.000000
unique      4        NaN       3        NaN
top     Alice        NaN  Lahore        NaN
freq        1        NaN       2        NaN
mean      NaN  29.500000     NaN  88.750000
std       NaN   4.203173     NaN   6.714412
min       NaN  25.000000     NaN  79.500000
25%       NaN  27.250000     NaN  86.250000
50%       NaN  29.000000     NaN  90.250000
75%       NaN  31.250000     NaN  92.750000
max       NaN  35.000000     NaN  95.000000

In [7]:
print("Mean age:", df['Age'].mean())
print("Max score:", df['Score'].max())
print()
print(df['City'].value_counts())

Mean age: 29.5
Max score: 95.0

City
Lahore       2
Karachi      1
Islamabad    1
Name: count, dtype: int64

## Common methods used very frequently

`.head(n)` / `.tail(n)` preview the first or last rows, `.shape` gives (rows, columns), and `.info()` summarizes column types and non missing counts. `.loc[]` selects by label and `.iloc[]` selects by position. Boolean filtering, for example `df[df['Age'] > 28]`, keeps only rows matching a condition, and `.isna()`, `.dropna()`, `.fillna()` handle missing values.

In [8]:
print(df.head(2))
print()
print("Shape:", df.shape)

    Name  Age     City  Score
0  Alice   25   Lahore   88.5
1    Bob   30  Karachi   92.0

Shape: (4, 4)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
 3   Score   4 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 260.0+ bytes

In [24]:
print("loc, row 0:\n", df.loc[3])
print()
print("iloc, first two rows and columns:\n", df.iloc[0:1, 0:3])

loc, row 0:
 Name      Diana
Age          28
City     Lahore
Score      95.0
Name: 3, dtype: object

iloc, first two rows and columns:
     Name  Age    City
0  Alice   25  Lahore

In [11]:
# Boolean filtering
print(df[(df['City'] == 'Lahore') & (df['Score'] > 85)])

    Name  Age    City  Score
0  Alice   25  Lahore   88.5
3  Diana   28  Lahore   95.0

In [12]:
# Missing data
df_missing = df.copy()
df_missing.loc[1, 'Score'] = np.nan

print("Missing count per column:\n", df_missing.isna().sum())
print()
print("Filled:\n", df_missing.fillna({'Score': df_missing['Score'].mean()}))

Missing count per column:
 Name     0
Age      0
City     0
Score    1
dtype: int64

Filled:
       Name  Age       City      Score
0    Alice   25     Lahore  88.500000
1      Bob   30    Karachi  87.666667
2  Charlie   35  Islamabad  79.500000
3    Diana   28     Lahore  95.000000

## Creating new columns and renaming columns

Assigning to a new column name, for example `df['Passed'] = df['Score'] >= 80`, creates a new column, either from a constant, a calculation on existing columns, or a separate list or Series. Pandas computes these values once at that moment, they are not live formulas, so changing the original column later will not update anything derived from it earlier. `.rename(columns={...})` renames columns and returns a new DataFrame unless you pass `inplace=True`.

In [13]:
df2 = df.copy()
df2['Passed'] = df2['Score'] >= 80
df2['Age_in_5_years'] = df2['Age'] + 5
df2

      Name  Age       City  Score  Passed  Age_in_5_years
0    Alice   25     Lahore   88.5    True              30
1      Bob   30    Karachi   92.0    True              35
2  Charlie   35  Islamabad   79.5   False              40
3    Diana   28     Lahore   95.0    True              33

In [14]:
# Derived columns are not live formulas
df2['Doubled_age'] = df2['Age'] * 2
df2['Age'] = df2['Age'] + 1
print("Doubled_age did NOT update automatically:")
print(df2[['Age', 'Doubled_age']])

Doubled_age did NOT update automatically:
   Age  Doubled_age
0   26           50
1   31           60
2   36           70
3   29           56

In [15]:
renamed = df2.rename(columns={'Name': 'Full_Name', 'Age': 'Current_Age'})
print(renamed.columns.tolist())

['Full_Name', 'Current_Age', 'City', 'Score', 'Passed', 'Age_in_5_years', 'Doubled_age']

## Changing the layout and sorting

`.sort_values(by=column)` sorts rows by one or more columns, with `ascending=False` for descending order. `.groupby()`  splits data into groups, applies an aggregation, and combines the results, the classic split, apply, combine pattern.

In [26]:
print(df.sort_values(by='Score', ascending=False))

      Name  Age       City  Score
3    Diana   28     Lahore   95.0
1      Bob   30    Karachi   92.0
0    Alice   25     Lahore   88.5
2  Charlie   35  Islamabad   79.5

In [17]:
print(df.groupby('City')['Score'].mean())

City
Islamabad    79.50
Karachi      92.00
Lahore       91.75
Name: Score, dtype: float64

## A few other essential tools

`pd.read_csv()` and `df.to_csv()` read and write CSV files. `pd.merge(left, right, on='key')` joins two DataFrames on a shared column, similar to a SQL join. A single column, `df['Score']`, returns a Series, while a list of columns, `df[['Name', 'Score']]`, returns a DataFrame. `.apply()` runs a custom function across every row or column.

In [ ]:
df.to_csv('sample_data.csv', index=False)
pd.read_csv('sample_data.csv')

      Name  Age       City  Score
0    Alice   25     Lahore   88.5
1      Bob   30    Karachi   92.0
2  Charlie   35  Islamabad   79.5
3    Diana   28     Lahore   95.0

In [19]:
customers = pd.DataFrame({'CustomerID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
orders = pd.DataFrame({'OrderID': [101, 102, 103], 'CustomerID': [1, 2, 1], 'Amount': [250, 400, 150]})

pd.merge(customers, orders, on='CustomerID')

   CustomerID   Name  OrderID  Amount
0           1  Alice      101     250
1           1  Alice      103     150
2           2    Bob      102     400

In [20]:
def score_category(score):
    return 'Excellent' if score >= 90 else 'Good' if score >= 80 else 'Needs Improvement'

df3 = df.copy()
df3['Category'] = df3['Score'].apply(score_category)
df3

      Name  Age       City  Score           Category
0    Alice   25     Lahore   88.5               Good
1      Bob   30    Karachi   92.0          Excellent
2  Charlie   35  Islamabad   79.5  Needs Improvement
3    Diana   28     Lahore   95.0          Excellent